#!/usr/bin/expect -f
set password "Nocturnal3am."
spawn ssh -p 65002 u240557956@153.92.11.7
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}
expect "$ "
send "cd domains/studiotigapagi.com/public_html\r"
expect "$ "
send "git restore .\r"
expect "$ "
send "git pull origin Nocturnal3am\r"
expect "$ "
send "npm run build\r"
expect "$ "
send "php artisan optimize:clear\r"
expect "$ "
send "exit\r"
expect eof
