#!/usr/bin/expect -f
set timeout -1
set password "Nocturnal3am."
spawn ssh -p 65002 u240557956@153.92.11.7
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}
expect "$ "
send "chmod 755 domains/studiotigapagi.com/public_html/public/img/client_all/\r"
expect "$ "
send "chmod 644 domains/studiotigapagi.com/public_html/public/img/client_all/*\r"
expect "$ "
send "exit\r"
expect eof
