#!/usr/bin/expect -f
set timeout -1
set password "Nocturnal3am."
spawn ssh -p 65002 u240557956@153.92.11.7
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}
expect "$ "
send "sed -i 's/^DB_PORT=.*/DB_PORT=3306/' domains/studiotigapagi.com/public_html/.env\r"
expect "$ "
send "sed -i 's/^DB_DATABASE=.*/DB_DATABASE=u240557956_tigapagi/' domains/studiotigapagi.com/public_html/.env\r"
expect "$ "
send "sed -i 's/^DB_USERNAME=.*/DB_USERNAME=u240557956_nocturnal/' domains/studiotigapagi.com/public_html/.env\r"
expect "$ "
send "sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=Nocturnal3am/' domains/studiotigapagi.com/public_html/.env\r"
expect "$ "
send "php domains/studiotigapagi.com/public_html/artisan config:clear\r"
expect "$ "
send "exit\r"
expect eof
